# Generated by Django 2.0.4 on 2018-07-25 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20180724_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnums',
            name='blog',
        ),
        migrations.DeleteModel(
            name='ReadNums',
        ),
    ]
